### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by brettz9** [dragfyre/bahai-date-api#14]
Should latitude/longitude and timezone arguments be accepted?

I would also think the default should be 'Akká, Israel.

**Comment by dragfyre** [comment]
How exactly would this work? It's an interesting suggestion, I just don't know how we'd go about it.

**Comment by brettz9** [comment]
Just another GET argument. I've have to look at the badidate API again on the format expected, but I don't think there is any problem doing it.
