### ISSUE TITLE
Is there a public endpoint for this API?

### ISSUE THREAD

**Issue by kennyr87** [dragfyre/bahai-date-api#15]
Thank you for making this project available. We'd like to use this API as public endpoint for Gregorian to Badi date conversion. Is there an endpoint already available?

**Comment by brettz9** [comment]
Is see there is https://www.openode.io/docs/platform/open_source.md that might be used for free open source hosting, but it has the requirement "Must be active on a monthly basis.".

@dragfyre : I could possibly host this on https://bahai-browser.org (currently a Chrome-only experimental website, but I could set aside a folder for this if you didn't have a place for it). Off topic, but I forget if you are keen to review or whether you want me to just go ahead and merge my existing PRs?

**Comment by kennyr87** [comment]
ok, thanks @brettz9. i think openode.io could be a good solution. i don't quite know yet what our api resource usage would be, but we should be making requests on a regular basis. 

i'm working with a group of friends to build a calendar app to help local communities better manage events and synchronize community life with the Badí calendar. @ketman-io, whom I'm working with to build the app, offered to host an instance using GCP's infrastructure. so please don't feel the need to incur any extra costs to run the service.

**Comment by dragfyre** [comment]
There have been a couple of offers to host this API more or less permanently; let me chase down the people who need to be chased down and I'll get back to this thread when it's done.

**Comment by dragfyre** [comment]
@kennyr87 For the time being, I think we'll look into getting this set up on bahai-browser.org as @brettz9 said. If/when the API gets enough usage, we can try and move it to openode.io.

**Comment by dragfyre** [comment]
@kennyr87 The API now has a public endpoint here on bahai-browser.org:

date/ - https://bahai-browser.org/date
today/ - https://bahai-browser.org/today
